name: Update INDEX

on:
  push:
    branches:
      - main
    paths:
      - 'dictionnaire/**'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install markdown2

      - name: Update INDEX.md
        run: python scripts/update_index.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add INDEX.md
          git commit -m "Automatically update INDEX.md" -a || echo "No changes to commit"
          git push
